name: Throat

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Start Redis
      uses: supercharge/redis-github-action@1.2.0
      with:
        redis-version: ${{ matrix.redis-version }}
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - uses: actions/setup-node@v2
      with:
        node-version: '12'
    - name: Install dependencies
      run: |
        python -m pip install poetry
        poetry config virtualenvs.create false
        poetry install
    - name: Check Black formatting
      run: pre-commit run --all-files
    - name: Install node deps
      run: npm install
    - name: Build JS bundles
      run: npm run build
    - name: Test with pytest
      run: |
        pytest
